### ISSUE TITLE
[FEATURE] CRAN Release

### ISSUE THREAD

**Issue by csgillespie** [sonatype-nexus-community/oysteR#14]
* **What are you trying to do?**

Get a version of the package on CRAN

* **What feature or behavior is this required for?**

That's how people get R packages

* **How could we solve this issue? (Not knowing is okay!)**

Fix the following issues:

- [x] Licences #7 
- [X] Message on load #6
- [x] Add travis support
- [x] Add a few more examples to the docs
- [x] Merge/delete the other [branch](https://github.com/sonatype-nexus-community/oysteR/tree/ReleaseBranch)

Once those are fixed then

- [x] Upload and check the package on [win builder](https://win-builder.r-project.org/)
- [x] Bump version to 0.1.0
- [x] Submit to CRAN

* **Anything else?**

cc @bhamail / @DarthHater / @brittanybelle / @adrianpowell / @csgillespie

**Comment by DarthHater** [comment]
Travis support is just to get it building on multiple R versions yes?

**Comment by csgillespie** [comment]
Yep. Just allows automatic testing on three different versions of R.

**Comment by csgillespie** [comment]
Nudging @DarthHater

**Comment by DarthHater** [comment]
@csgillespie are you free one of these days to get on a hangout or something akin and work together on this? We might be able to cruise through the rest of the obstacles together!

**Comment by csgillespie** [comment]
What about Thursday - email is csgillespie@gmail.com

**Comment by DarthHater** [comment]
Thursday sounds great! I'll send you an email.

**Comment by bhamail** [comment]
😄 It's on CRAN!  https://cran.r-project.org/web/packages/oysteR/index.html
