### ISSUE TITLE
How often is the sonatype database updated?

### ISSUE THREAD

**Issue by csgillespie** [sonatype-nexus-community/oysteR#19]
Basically, how often to check cran for new packages/versions.

**Comment by DarthHater** [comment]
@ken-duck would know the specifics. We had I believe the ingest happening nightly, but there can be hiccups from time to time. @ken-duck @brittanybelle @ndonewar and myself have been doing some work to make this process a bit better though!

**Comment by csgillespie** [comment]
Is this information available via the API or some other method?

**Comment by DarthHater** [comment]
Not as of now, I think @brittanybelle or @ndonewar could comment further on that.

**Comment by brittanybelle** [comment]
Sorry for the delayed response! At the moment the CRAN package ingest is happening on an ad-hoc basis while we figure out an automated process.

I should note that the CRAN ingest for OSS Index would only affect component metadata (mainly package description). Our vulnerability records are updated on a more regular basis through a separate process.
