### ISSUE TITLE
Provide a means of displaying vuln info in Rmd 

### ISSUE THREAD

**Issue by hrbrmstr** [sonatype-nexus-community/oysteR#2]
Posit:

Provide a function like `cloc::cloc_pkg_md()` which can be placed in Rmd block (e.g. in README.Rmd)):

![image](https://user-images.githubusercontent.com/509878/76169746-b0856980-6151-11ea-929a-d8af2fe31f34.png)

that would enable visually appealing display of vuln status (like that `cloc` function does here):

![image](https://user-images.githubusercontent.com/509878/76169759-ce52ce80-6151-11ea-9ae4-f7eda9b6ec81.png)

(you can see that source and display here: https://git.rud.is/hrbrmstr/ssdeepr)

I can PR ^^ into this pretty easily.

Separate posit (I can make it a sep issue):

Provide an RStudio addin with the pkg that folks can set a keybinding to for a quick vuln check.

I've pre-signed the CLA, too.

**Comment by DarthHater** [comment]
Send a PR over for sure! The relationship of package to vulnerability is 1:0-many, in case that helps!

**Comment by hrbrmstr** [comment]
gotcha. will do later this week.

many thanks for Sonatype adding in the R ecosystem despite the fact that virtually nobody is looking at vulns there (besides myself and Colin :-)

**Comment by csgillespie** [comment]
@hrbrmstr I've made a few updates to this package.

I'm not quite sure I understand what you are after (sorry). Can you provide more details?

**Comment by csgillespie** [comment]
Not really sure what this means, so closing.
