### ISSUE TITLE
Update README to illustrate new functionality

### ISSUE THREAD

**Issue by JosiahParry** [sonatype-nexus-community/oysteR#31]
Given that `audit_deps()` has been moved to a deprecated status and the addition of new functionality, the README ought to be modified to reflect these changes.

**Comment by csgillespie** [comment]
Do you mean the docs (which I have noticed are wrong) or the README?

**Comment by JosiahParry** [comment]
Specifically the README.

**Comment by csgillespie** [comment]
Ahh sorry. I was looking for a mistake, it's more lack of documentation
