### ISSUE TITLE
Move from Travis.org to Travis.com

### ISSUE THREAD

**Issue by csgillespie** [sonatype-nexus-community/oysteR#34]
travis.org is depreciated and I think is getting switched off at Christmas. 

cc @bhamail / @DarthHater / @brittanybelle / @adrianpowell / @csgillespie

**Comment by zendern** [comment]
I think most other products are now using circleci so would it make sense to just put the effort into moving to that??

**Comment by csgillespie** [comment]
The trade-off we have is:

 * [travis](https://github.com/sonatype-nexus-community/oysteR/blob/master/.travis.yml) is well supported. So our current CI checks against three versions of R and works out code coverage
 * [circle ci](https://github.com/sonatype-nexus-community/oysteR/blob/master/.circleci/config.yml) isn't native, so we have to mess about with Docker. This CI only checks against R past

R + Github actions is relatively well supported.

**Comment by DarthHater** [comment]
Yeah, for `oysteR` it makes perfect sense to stick with Travis-CI. They have great R support.

**Comment by csgillespie** [comment]
Done thanks to @DarthHater & @bhamail
