### ISSUE TITLE
Merge Release Branch to Dev 

### ISSUE THREAD

**Issue by csgillespie** [sonatype-nexus-community/oysteR#4]
I think it's only the circle CI that needs to merged. 

I don't use circle CI, so if someone else could do this.

**Comment by DarthHater** [comment]
@csgillespie , @brittanybelle and I took a gander today, and we love what you did. We think that this could likely go directly into master. The only caveat is that we figure out the failing test in #8 !

**Comment by brittanybelle** [comment]
> we love what you did

+1 to @DarthHater 's comment! It is very enlightening to learn what a "real R user" would look for in a vulnerability scanning library, thanks so much for your involvement!

**Comment by csgillespie** [comment]
Fixed the bug #8.

**Comment by csgillespie** [comment]
Done via 59ba4d77535bd00eb9e4fd63fa4e565cdd1d3cef
