### ISSUE TITLE
Create pkgdown site for easy consumption of manual w/out downloading

### ISSUE THREAD

**Issue by JosiahParry** [sonatype-nexus-community/oysteR#40]
* **What are you trying to do?**

I would like to be able to have a website to point folks to for oysteR. 

* **What feature or behavior is this required for?**

A single URL that contains function documentation as well as user vignettes. 

* **How could we solve this issue? (Not knowing is okay!)**

Using pkgdown

* **Anything else?**

cc @bhamail / @DarthHater / @brittanybelle / @adrianpowell / @csgillespie

**Comment by csgillespie** [comment]
Great issue @JosiahParry I'm waiting for @DarthHater to move from travis.org to travis.com (#34) before adding this.

@DarthHater consider this a gentle prod :)

**Comment by JosiahParry** [comment]
🙃

**Comment by JosiahParry** [comment]
Would it help to have a PR with a package down site at the ready? ;)

**Comment by csgillespie** [comment]
Sure!
