### ISSUE TITLE
Add website link to repository 

### ISSUE THREAD

**Issue by JosiahParry** [sonatype-nexus-community/oysteR#45]
* **What are you trying to do?**
  - add the website url to GH repository for docs discovery and exploration

* **What feature or behavior is this required for?**
  - communicating with the general public 

* **How could we solve this issue? (Not knowing is okay!)**
  - modify the url in GH repo settings

* **Anything else?**

cc @bhamail / @DarthHater / @brittanybelle / @adrianpowell / @csgillespie

**Comment by csgillespie** [comment]
@bhamail / @DarthHater Can you add https://sonatype-nexus-community.github.io/oysteR/ as the website? 

Click the cog next to "About" on the front page to add.

**Comment by bhamail** [comment]
Done did.

**Comment by JosiahParry** [comment]
Woooot!
