### ISSUE TITLE
[FEATURE] Export generate_purls or generate_purl

### ISSUE THREAD

**Issue by DarthHater** [sonatype-nexus-community/oysteR#53]
* **What are you trying to do?**
Purls are an implementation of the purl-spec, and being you have written the code to generate a purl, I thought you might be interested in exposing it as a part of the library.

You can potentially get listed here as a known implementation:

https://github.com/package-url/purl-spec#known-implementations

* **What feature or behavior is this required for?**

It would give people writing R a library to use to construct a purl from known coordinates.

* **How could we solve this issue? (Not knowing is okay!)**
Expose the functions?

* **Anything else?**
Up to you! Just an idea! You could also just create a more generic library for creating purls, if you wanted to implement all the known types, too.

cc @bhamail / @DarthHater / @brittanybelle / @adrianpowell / @csgillespie

**Comment by JosiahParry** [comment]
Exporting it is a rather easy feat. I think we can do that. But prior to that i think it would make sense to get some validation functions in there. I'm not sure if it is worth spinning off into its own package, though. @csgillespie, thoughts on that? I suppose it would make sense to extend to bioC. I'm not sure of any other major R package repository besides those two.

**Comment by csgillespie** [comment]
I think this is handled via the `audit()` function. You can pass arbitraryy pkgs, versions and types. 

https://github.com/sonatype-nexus-community/oysteR/blob/master/R/audit.R#L35
