### ISSUE TITLE
Remove Fuzzy matching on missing Purls

### ISSUE THREAD

**Issue by csgillespie** [sonatype-nexus-community/oysteR#59]
If a version is missing, we add a * to the version number - which is wrong! See #58 for info

**Comment by JosiahParry** [comment]
The thing about this is that it _actually_ works for things like Python! 

For example try the below. 

```
purl <- oysteR:::generate_purls("django", "*", "pypi")

oysteR:::call_oss_index(purl, TRUE)
```
