### ISSUE TITLE
Dev: Message on load

### ISSUE THREAD

**Issue by csgillespie** [sonatype-nexus-community/oysteR#6]
Do you want:
```
onAttach = function(...) { #nolint
  if (!interactive()) return()
  packageStartupMessage("See https://www.sonatype.com/ for details.")
```
See https://github.com/sonatype-nexus-community/oysteR/pull/3 for brief discussion

**Comment by DarthHater** [comment]
I'm mostly curious, what does this do? Hah. I know I can pull the code down and look at it, just curious overall.

**Comment by csgillespie** [comment]
So this is the mechanism that people _should_ use to display start-up messages.

 * The interactive() makes sure the message is only displayed in interactive mode, e.g. not Rscript
 * The `packageStartupMessage()` provides a clean way of turning it off
 * The zzz.R is just historical (file order used to matter more)
 * onAttach runs only the first time the package is attached to the search path

In R, the message will get displayed when you type
```
library(osyteR)
```
As we've done it "properly", the message can be hidden using standard mechanisms

 * suppressPackageStartupMessages
 * message = FALSE in knitr chunks

Up to you if you want it. I just copied your start-up message.

**Comment by DarthHater** [comment]
I'll give it a twirl in a bit! Thanks for explaining!

**Comment by csgillespie** [comment]
I've added the URL to the verbose output - https://github.com/sonatype-nexus-community/oysteR/commit/581cabe0849c5674592cb27088015596dff30ec6 This is a lot less intrusive

So just delete zzz.R?

**Comment by DarthHater** [comment]
I think we fixed a bit of this on the `dev` branch @csgillespie , @brittanybelle and I changed the link to the link for this repo (instead of our corporate website). Wanna take a gander and maybe close this?
