### ISSUE TITLE
Dev: Add test suite

### ISSUE THREAD

**Issue by csgillespie** [sonatype-nexus-community/oysteR#8]
Need test for `call_oss_index()`

**Comment by DarthHater** [comment]
@csgillespie , hey! @brittanybelle and I added this test back in today, and we got it to fail, which is great.

We noticed that when we run it, the test shows 95 total projects, but if it's truly using the saved json it should be 99. This may or may not be related to your changes, so it might be worth a look!

Cheers!

**Comment by csgillespie** [comment]
Good spot! The issue is due to the API not always returning a description (https://github.com/sonatype-nexus-community/oysteR/blob/master/tests/testthat/ossindex.sonatype.org/api/v3/component-report-cb1057-POST.json#L353)

---
Fix to follow.
